apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      container: worker
  template:
    metadata:
      labels:
        container: worker
    spec:
      containers:
        - name: worker
          image: stephengrider/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-clustser-ip-service
            - name: REDIS_PORT
              value: 6379
          